### PR TITLE
Fixes syntax error

### LINKED ISSUE #8: Does not work anymore
`buzzoff.js:12 Uncaught SyntaxError: missing ) after argument list`

### PR DESCRIPTION
**Pull request by clarkb7**
fixes #8

### CODE REVIEW

**Comment by TheoBr** [comment]
Lol I was under the impression that this didn't work at the moment, thanks for fixing a bracket!

**Comment by TheoBr** [comment]
If you want to see some real syntax errors, check out [Chrometana](https://github.com/TheoBr/Chrometana). I made quite a mess over there

**Comment by clarkb7** [comment]
Looks like you closed but didn't merge it

**Comment by t3dotgg** [comment]
Github can't process clicks out of order

**Pull request merged**
